set number
syntax on

" colorscheme
" cp ~/.vim/plugged/vim-hybrid/colors/hybrid.vim .
colorscheme darcula

let mapleader=','

" inoremap jj <Esc>`^

inoremap <leader>w <Esc>:w<cr>
noremap <leader>w :w<cr>

noremap <C-h> <C-w>h
noremap <C-l> <C-w>l
noremap <C-k> <C-w>k
noremap <C-j> <C-w>j

call plug#begin('~/.vim/plugged')

Plug 'mhinz/vim-startify'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Yggdroot/indentLine'
" theme
Plug 'blueshirts/darcula'
Plug 'scrooloose/nerdtree'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-surround'
" fzf
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'brooth/far.vim'
Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'develop' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'lfv89/vim-interestingwords'
" for git
Plug 'tpope/vim-fugitive'
Plug 'junegunn/gv.vim'
Plug 'airblade/vim-gitgutter'


" for deoplete
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

Plug 'deoplete-plugins/deoplete-jedi'

" format
Plug 'sbdchd/neoformat'

" lint
Plug 'w0rp/ale'
Plug 'tpope/vim-commentary'

" go
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

call plug#end()

" ctrlp
" let g:ctrlp_map = '<c-p>'

" for nerdtree
nmap <leader>v :NERDTreeFind<cr>
nmap <leader>g :NERDTreeToggle<cr>
let NERDTreeShowHidden=1
let NERDTreeIgnore = [
            \ '\.git$', '\.hg$', '\.svn$', '\.stversions$', '\.pyc$', '\.pyo$', '\.svn$', '\.swp$',
            \ '\.DS_Store$', '\.sass-cache$', '__pycache__$', '\.egg-info$', '\.ropeproject$',
            \ ]

" for easy-motion
nmap ss <Plug>(easymotion-s2)

" python mode
let g:python3_host_prog = '/usr/local/bin/python3'
let g:pymode_python = 'python3'
let g:pymode_trim_whitespaces = 1
let g:pymode_doc=1
let g:pymode_doc_bind = 'K'
let g:pymode_syntax = 1 " 开启 pymode 语法高亮
let g:pymode_rope = 1 " 关键 可以生成项目缓存 然后实现定义跳转
let g:pymode_motion = 1 " 开启 pymode 跳转
let g:pymode_virtualenv = 1 " 自动激活虚拟环境
let g:pymode_rope_goto_definition_bind = "<C-]>"
let g:pymode_lint = 1
let g:pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe', 'pylint']
" let g:pymode_lint_ignore = "C0111, W0105, C0325"
let g:pymode_lint_ignore = "E402"
let g:pymode_options_max_line_length = 120

" tagbar
nnoremap <leader>t :TagbarToggle<cr>

" for deoplete
let g:deoplete#enable_at_startup = 1
set completeopt-=preview

" neoformat
let g:neoformat_enabled_python = ['autopep8']

" gitgutter
set updatetime=100

